# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETD0FfWuW-e-D_KjawaAq2omIuA2XUCK
"""

import os
import re
import json
from pathlib import Path

import pandas as pd
import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

BASE_MODEL = os.getenv("BASE_MODEL", "Qwen/Qwen2.5-3B-Instruct")
MAX_NEW_TOKENS = int(os.getenv("MAX_NEW_TOKENS", "1024"))
QUANT_MODE = os.getenv("QUANT_MODE", "4bit")

st.set_page_config(page_title="Interview Coding Assistant", layout="wide")
st.title("Автоматическая разметка интервью")
st.markdown("---")

def build_prompt_h2(example, tokenizer):
    """Формирует промт (query) как в исходном build_prompt, но без ответа"""
    instruction = f"""You are an expert in interview analysis. Your task is to highlight the thematic codes in the interview text and corresponding quotes.

Act step by step:

1. Carefully review the output format shown in the example below. Remember that each code block must contain "Общий код" (General code), then Quote, then "Конкретный код" (Specific code). The quote must be verbatim and enclosed in quotation marks.
2. Read the interview transcript and the topic. Identify all fragments (quotes) that relate to the interview topic.
3. Group the quotes by general themes — these will be the "Общий код" (General codes). For each general theme, come up with a short name.
4. Within each general code, identify specific meaning aspects — these will be the "конкретный код" (Specific codes). The names of specific codes should reflect the essence of the quote.
5. Generate the answer strictly following the format from the example. Do not add any explanations, do not write words like 'Step 1', 'Step 2' — only the final blocks of codes and quotes.

Format of an output (consists of several general codes, each followed by quotes and specific codes):
**Общий код 1: <generate general code 1>**
"<quote text>" - **<generate specific code 1> (Конкретный код)**
"<quote text>" - **<generate specific code 2> (Конкретный код)**
**Общий код 2: <generate general code 2>**
"<quote text>" - **<generate specific code> (Конкретный код)**
**Общий код <general code number>: <generate general code>**
"<quote text>" - **<generate specific code> (Конкретный код)**
and so on. You choose the number of general and specific codes.

Now you should do the markup for the interview according to the plan. Important: The answer should contain only codes and quotes, without unnecessary words and repetitions.
The quotes must be strictly from the text. Give the answer in Russian.
"""

    user_content = f"""Тема интервью:
{example['topic']}

Текст интервью:
{example['transcript']}

Пожалуйста, выполни разметку интервью, каждый общий код в указанном формате:
**Общий код <generate general code>: <general code name>**
"<quote text>" - **<generate specific code> (Конкретный код)**"""

    messages = [
        {"role": "system", "content": instruction},
        {"role": "user", "content": user_content},
    ]
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    return prompt

@st.cache_resource(show_spinner="Загрузка модели, подождите...")
def load_model():
    try:
        tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)

        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        if tokenizer.pad_token_id is None:
            tokenizer.pad_token_id = tokenizer.eos_token_id

        bnb_cfg = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
        )

        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL,
            quantization_config=bnb_cfg,
            device_map="auto",
            trust_remote_code=True,
            torch_dtype=torch.float16,
        )

        model.eval()
        return tokenizer, model

    except Exception as e:
        st.error(f"Ошибка загрузки модели: {str(e)}")
        raise

def generate(
    tokenizer,
    model,
    topic: str,
    transcript: str,
    max_new_tokens: int,
    num_beams: int,
    repetition_penalty: float,
    no_repeat_ngram_size: int
) -> str:
    example = {
        "topic": topic.strip(),
        "transcript": transcript.strip()
    }

    prompt = build_prompt_h2(example, tokenizer)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=3600
    ).to(model.device)

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=num_beams,
            repetition_penalty=repetition_penalty,
            no_repeat_ngram_size=no_repeat_ngram_size,
            early_stopping=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip()

    generated = generated.split("<|im_end|>")[0].strip()

    if generated.startswith("system"):
        generated = ""
    elif generated.startswith("user"):
        generated = ""

    return generated

def parse_output(raw_text: str) -> list:
    rows = []
    current_general = ""
    lines = raw_text.split("\n")

    for line in lines:
        line = line.strip()
        if not line:
            continue

        general_pattern = r'\*{0,2}Общий код\s*\d+\s*[:\-]\s*(.+?)\*{0,2}$'
        match_general = re.match(general_pattern, line, re.IGNORECASE)
        if match_general:
            current_general = match_general.group(1).strip().strip('*').strip()
            continue

        quote_pattern = r'^["“«](.+?)["”»]\s*[-–—]\s*\*{0,2}(.+?)\*{0,2}$'
        match_quote = re.match(quote_pattern, line)
        if match_quote and current_general:
            rows.append({
                "Общий код": current_general,
                "Конкретный код": match_quote.group(2).strip(),
                "Цитата": match_quote.group(1).strip(),
            })
        elif current_general and (line.startswith('"') or line.startswith('“') or line.startswith('«')):
            quote = line.strip('"“”«»').strip()
            if quote:
                rows.append({
                    "Общий код": current_general,
                    "Конкретный код": "",
                    "Цитата": quote,
                })

    return rows

def validate_parsed_data(rows: list) -> bool:
    if not rows:
        return False
    for row in rows:
        if not row.get("Общий код") or not row.get("Цитата"):
            return False
    return True

with st.sidebar:
    st.header("Параметры генерации")

    num_beams = 2

    repetition_penalty = st.slider(
        "repetition_penalty",
        min_value=1.0,
        max_value=2.0,
        value=1.5,
        step=0.1,
        help="Штраф за повторения (больше = меньше повторений)"
    )

    no_repeat_ngram_size = st.slider(
        "no_repeat_ngram_size",
        min_value=0,
        max_value=8,
        value=4,
        help="Размер n-граммы, которую нельзя повторять"
    )

    max_new_tokens = st.slider(
        "max_new_tokens",
        min_value=256,
        max_value=1024,
        value=MAX_NEW_TOKENS,
        step=64,
        help="Максимальное количество генерируемых токенов"
    )

    st.divider()
    st.subheader("Информация о модели")
    st.caption(f"**Модель:** {BASE_MODEL.split('/')[-1]}")
    st.caption(f"**Квантизация:** {QUANT_MODE}")
    st.caption("**Адаптер:** не используется")
    st.divider()
    st.markdown("""
    **Инструкция:**
    1. Введите тему исследования
    2. Вставьте транскрипт интервью
    3. Нажмите "Разметить"
    4. Скачайте результат в CSV или JSON
    """)

topic = st.text_area(
    "Тема исследования",
    height=100,
    placeholder="Например: Поколенческая идентичность, жизненные выборы и устойчивость российской молодежи",
    help="Укажите основную тему интервью"
)

transcript = st.text_area(
    "Текст интервью",
    height=400,
    placeholder="Вставьте транскрипт интервью сюда...\n\nИнтервьюер: Вопрос...\nИнформант: Ответ...",
    help="Вставьте полный транскрипт интервью с репликами"
)

col1, col2, col3 = st.columns([1, 1, 4])
transcript = transcript[:6200]
run_btn = col1.button("Разметить", type="primary", use_container_width=True)
clear_btn = col2.button("Очистить", use_container_width=True)

if clear_btn:
    st.rerun()

try:
    tokenizer, model = load_model()
except Exception:
    st.stop()

if run_btn:
    if not topic.strip():
        st.error("Укажите тему исследования.")
    elif not transcript.strip():
        st.error("Вставьте текст интервью.")
    else:
        with st.spinner("Генерация разметки... Это может занять несколько минут."):
            try:
                raw_output = generate(
                    tokenizer,
                    model,
                    topic,
                    transcript,
                    max_new_tokens,
                    num_beams,
                    repetition_penalty,
                    no_repeat_ngram_size,
                )

                with st.expander("Сырой ответ модели", expanded=False):
                    st.code(raw_output, language="markdown")

                st.subheader("Структурированная разметка")
                parsed_rows = parse_output(raw_output)

                if parsed_rows and validate_parsed_data(parsed_rows):
                    df = pd.DataFrame(parsed_rows)

                    st.dataframe(
                        df,
                        use_container_width=True,
                        column_config={
                            "Общий код": st.column_config.TextColumn("Общий код", width="medium"),
                            "Конкретный код": st.column_config.TextColumn("Конкретный код", width="large"),
                            "Цитата": st.column_config.TextColumn("Цитата", width="large"),
                        }
                    )

                    st.info(f"Размечено: {len(parsed_rows)} фрагментов | {df['Общий код'].nunique()} уникальных общих кодов")

                    col_dl1, col_dl2, _ = st.columns([1, 1, 2])
                    with col_dl1:
                        st.download_button(
                            "Скачать CSV",
                            df.to_csv(index=False).encode("utf-8-sig"),
                            "interview_coding.csv",
                            "text/csv",
                            help="Скачать результат в формате CSV"
                        )
                    with col_dl2:
                        st.download_button(
                            "Скачать JSON",
                            json.dumps(parsed_rows, ensure_ascii=False, indent=2).encode("utf-8"),
                            "interview_coding.json",
                            "application/json",
                            help="Скачать результат в формате JSON"
                        )
                else:
                    st.warning("Не удалось распарсить структуру ответа. Проверьте формат вывода модели.")
                    st.markdown("**Сырой ответ модели:**")
                    st.code(raw_output, language="markdown")

            except Exception as e:
                st.error(f"Ошибка при генерации: {str(e)}")
                st.info("Попробуйте уменьшить параметры генерации или сократить текст интервью.")

st.markdown("---")
st.caption("Совет: Для лучших результатов используйте структурированные транскрипты с пометками 'Интервьюер:' и 'Информант:'")